Replace old global config with flask's config
YangCatalog/backend pull request #339
Opened 2021-08-18 14:09 UTC by richardzilincikPantheon

2021-08-19 07:14 UTC, richardzilincikPantheon commented
Converted to draft for now because I think I broke the sender

2021-08-19 07:38 UTC, richardzilincikPantheon commented
Looks like I didn't

2021-08-24 06:39 UTC, richardzilincikPantheon commented
Resolves #287

2021-08-24 12:36 UTC, SlavomirMazurPantheon requested changes

2021-08-24 12:36 UTC, SlavomirMazurPantheon commented on api/yangCatalogApi.py
> +
```
self.config['ES'] = Elasticsearch([{'host': '{}'.format(self.config.db_es_host), 'port': self.config.db_es_port}])
```

2021-08-24 12:36 UTC, SlavomirMazurPantheon commented on api/views/yangSearch/yangSearch.py
> +
Wrong log filename

2021-08-25 05:48 UTC, SlavomirMazurPantheon approved these changes

2021-08-25 05:48 UTC, merged