feat: replaced setUp methods with setUpClass where possible
YangCatalog/backend pull request #642
Opened 2022-10-31 08:59 UTC by Fagtoy

replaced setUp and tearDown methods with setUpClass and tearDownClass methods respectively, and also refactored formatting using f-strings in all tests.

2022-11-03 12:56 UTC, richardzilincikPantheon reviewed
Please merge the develop branch into this to fix the gevent issue in github actions so we can actually see the results.

2022-11-03 13:03 UTC, richardzilincikPantheon commented
oh sorry, I thought https://github.com/YangCatalog/backend/pull/642 was merged

2022-11-03 13:04 UTC, richardzilincikPantheon commented
done

2022-11-03 13:05 UTC, Fagtoy commented
> done

merged

2022-11-03 13:21 UTC, richardzilincikPantheon requested changes

2022-11-03 13:21 UTC, richardzilincikPantheon commented on tests/test_modules.py
> +# TODO: we should probably have unit tests for the individual Model._resolve* methods
This isn't relevant anymore since the resolves were moved to independent classes. Please remove it to avoid confusion.

2022-11-03 13:24 UTC, richardzilincikPantheon approved these changes

2022-11-04 07:50 UTC, SlavomirMazurPantheon approved these changes

2022-11-04 07:50 UTC, merged