style: documentation improvements
YangCatalog/backend pull request #754
Opened 2023-03-31 06:20 UTC by Fagtoy

Updated information in READMEs, and also rewrote the ```process-drafts.py``` script, so it uses ```DEFAULT_SCRIPT_CONFIG``` and not the ```ArgumentParser``` itself

2023-03-31 08:57 UTC, richardzilincikPantheon requested changes

2023-03-31 09:33 UTC, Fagtoy commented on README.md
> +Please note that UWSGI caching is used to improve the performance compared to ConfD requests. During loading of the UWSGI,
It seems like it's still being locked: https://github.com/YangCatalog/backend/blob/develop/api/yangCatalogApi.py#L163, changed to Redis

2023-03-31 11:38 UTC, Fagtoy commented on README.md
> +Please note that UWSGI caching is used to improve the performance compared to ConfD requests. During loading of the UWSGI,
yes, you are right, it just prevents different threads from reloading the cache, I removed this section entirely as it doesn't actually block any requests

2023-03-31 11:40 UTC, richardzilincikPantheon approved these changes

2023-04-03 07:34 UTC, SlavomirMazurPantheon approved these changes

2023-04-03 07:35 UTC, merged