Replace receiver with celery
YangCatalog/backend pull request #776
Opened 2023-05-25 08:25 UTC by Fagtoy

replaced sender/receiver with celery tasks

2023-05-26 11:20 UTC, richardzilincikPantheon requested changes
No important, but is there any advantage to using `.s().apply_async()` over `.delay()`?

2023-05-26 11:20 UTC, richardzilincikPantheon commented on jobs/jobs_information.py
> +    :return (tuple[str, str]) Returns the job status which can one of the following -
```suggestion
    :return (tuple[str, str]) Returns the job status which can be one of the following -
```

2023-05-26 12:08 UTC, Fagtoy commented on api/views/health_check.py
> +    message_mapping = {
Unfortunately, this status isn't helpful for us, as far as there's only one task can be run at a time, while one long-running task is being executed, other tasks in the queue will be in the PENDING state, so there's no difference for us if it's this task in PENDING or STARTED status, we assume that this task is "In Progress"

2023-05-26 12:12 UTC, Fagtoy commented
> No important, but is there any advantage to using `.s().apply_async()` over `.delay()`?

there's no advantage for now but if in the future the project needs more flexibility (different queues or some other configurations), then it's better to use apply_async, so I decided to use it now, so we assume it as the default calling method for the future

2023-05-29 06:26 UTC, richardzilincikPantheon approved these changes

2023-05-29 07:05 UTC, merged